services:
  localstack:
    profiles:
      - localstack
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    hostname: s3
    networks:
      default:
        aliases:
          - localstack_main
          - s3.localhost.localstack.cloud
    ports:
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 2s
      retries: 20
  web:
    read_only: false
    build:
      context: ${PWD}
      dockerfile: ${PWD}/${DOCKERFILE}
    image: doc-converter
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_BUCKET_NAME=doc-converter
      - AWS_QUEUE_NAME=doc-converter
    volumes:
      - "./upload.html:/var/www/html/upload.html"
      - "./upload.js:/var/www/html/upload.js"
      - "./upload.css:/var/www/html/upload.css"
      - "./jquery.tagsinput.css:/var/www/html/jquery.tagsinput.css"
      - "./jquery.tagsinput.js:/var/www/html/jquery.tagsinput.js"
    tty: true
    stdin_open: true
    ports:
      - '80:80'
    expose:
      - 80
