#!/usr/bin/env bash
# -*- mode: shell-script; -*-

set -euo pipefail

# Configuration
QUEUE_SCRIPT="/usr/local/bin/sqs-queue-processor.pl"
APACHE_BIN="/usr/sbin/apache2ctl"
LOGFILE="/var/log/sqs-doc-converter.log"

DIST_DIR=$(perl -MFile::ShareDir -e 'print File::ShareDir::dist_dir(q{DocConverter});');

if [[ -n "$AWS_ENDPOINT_URL" ]]; then
    aws s3 mb "s3://$AWS_BUCKET_NAME" --endpoint-url "$AWS_ENDPOINT_URL"
    aws sqs create-queue --queue-name "$AWS_QUEUE_NAME" --endpoint-url "$AWS_ENDPOINT_URL"
fi

# Start the queue daemon in the background
echo "[$(date +%FT%T)] Starting queue daemon..."
"$QUEUE_SCRIPT" --config $DIST_DIR/doc-converter-handler.yml >> "$LOGFILE" 2>&1 &

DAEMON_PID=$!

if [[ $(ps -p "$DAEMON_PID" -o pid -h | sed 's/[[:space:]]*//' ) = "$DAEMON_PID" ]]; then
    echo "[$(date +%FT%T)] Queue daemon started with PID: $DAEMON_PID"
else
    echo "Queue daemon failed to start properly."
    cat $LOGFILE
    exit 1;
fi

# Start Apache in the foreground
echo "[$(date +%FT%T)] Launching Apache in foreground..."
exec "$APACHE_BIN" -D FOREGROUND
